CREATE TABLE  "BOT_USERS" 
   (	"CHAT_ID" NUMBER NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(100), 
	"LAST_NAME" VARCHAR2(100), 
	"CRT" DATE, 
	"LOGIN" VARCHAR2(50), 
	"MDF" DATE, 
	"PIN" NUMBER, 
	 CONSTRAINT "BOT_USERS_PK" PRIMARY KEY ("CHAT_ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "BOT_SESSIONS" 
   (	"CHAT_ID" NUMBER NOT NULL ENABLE, 
	"TEXT" CLOB, 
	"MDF" DATE, 
	"ST" NUMBER(6,0), 
	"MENU" VARCHAR2(20), 
	 CONSTRAINT "BOT_SESSIONS_PK" PRIMARY KEY ("CHAT_ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "BOT_JOURN" 
   (	"CRT" DATE, 
	"CHAT_ID" NUMBER, 
	"METOD" VARCHAR2(20), 
	"BODY" CLOB, 
	"RESULT" CLOB, 
	"TOKEN" VARCHAR2(200)
   )
/
CREATE GLOBAL TEMPORARY TABLE  "REPLY_MARKUP_INLINE_KEYBOARD" 
   (	"TEXT" VARCHAR2(255) NOT NULL ENABLE, 
	"CALLBACK_DATA" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "REPLY_INLINE_UK1" UNIQUE ("CALLBACK_DATA") ENABLE
   ) ON COMMIT DELETE ROWS
/
CREATE TABLE  "BOT_AUDIO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"AUDIO" BLOB, 
	"AUDIO_FILENAME" VARCHAR2(512), 
	"AUDIO_MIMETYPE" VARCHAR2(512), 
	"AUDIO_CHARSET" VARCHAR2(512), 
	"AUDIO_LASTUPD" DATE, 
	"DESCR" VARCHAR2(4000), 
	 CONSTRAINT "BOT_AUDIO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE GLOBAL TEMPORARY TABLE  "REPLY_MARKUP_KEYBOARD" 
   (	"TEXT" VARCHAR2(255) NOT NULL ENABLE, 
	"REQUEST_CONTACT" NUMBER(1,0) DEFAULT 0, 
	"REQUEST_LOCATION" NUMBER(1,0), 
	 CONSTRAINT "REPLY_MARKUP_KEYBOARD_PK" PRIMARY KEY ("TEXT") ENABLE
   ) ON COMMIT DELETE ROWS
/
CREATE TABLE  "BOT_IMG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"IMG" BLOB, 
	"IMG_FILENAME" VARCHAR2(512), 
	"IMG_MIMETYPE" VARCHAR2(512), 
	"IMG_CHARSET" VARCHAR2(512), 
	"IMG_LASTUPD" DATE, 
	"DESCR" VARCHAR2(4000), 
	 CONSTRAINT "BOT_IMG_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "BOT_TASK" 
   (	"ID" NUMBER, 
	"TASK_TXT" VARCHAR2(4000), 
	"S_DATE" DATE, 
	"E_DATE" DATE, 
	"USER_M" NUMBER, 
	"USER_S" NUMBER, 
	"TASK_TP" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"REGION" NUMBER, 
	"DISTRICT" NUMBER, 
	"CITY" NUMBER, 
	"DISTRICT_OVO" NUMBER, 
	"AREA_VD" NUMBER, 
	"DESCR" VARCHAR2(4000), 
	 CONSTRAINT "BOT_TASK_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "BOT_ERR_JOURN" 
   (	"CRT" DATE, 
	"METOD" VARCHAR2(50), 
	"ERR_MSG" CLOB
   )
/
CREATE TABLE  "BOT_FILE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"THE_FILE" BLOB, 
	"FILE_FILENAME" VARCHAR2(512), 
	"FILE_MIMETYPE" VARCHAR2(512), 
	"FILE_CHARSET" VARCHAR2(512), 
	"FILE_LASTUPD" DATE, 
	"DESCR" VARCHAR2(4000), 
	 CONSTRAINT "BOT_FILE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "BOT_SETTING" 
   (	"TOKEN" VARCHAR2(199), 
	"WEBHOOK_URL" VARCHAR2(255), 
	"DEBUG" NUMBER(1,0), 
	"REST_URL" VARCHAR2(255), 
	 CONSTRAINT "BOT_SETTING_PK" PRIMARY KEY ("TOKEN")
  USING INDEX  ENABLE
   )
/
 CREATE SEQUENCE   "BOT_AUDIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "BOT_FILE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "BOT_IMG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "BOT_TASK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
