
-- Generated by ORDS REST Data Services 20.3.0.r3011819
-- Schema: TELEGRAM  Date: Sat Jan 09 05:41:58 2021 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'telegram',
      p_base_path      => '/telegram/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'telegram',
      p_pattern        => 'img/{id}',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'telegram',
      p_pattern        => 'img/{id}',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select img_mimetype,img  
from bot_img where id = :id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'telegram',
      p_pattern        => 'webhook/{token}',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'telegram',
      p_pattern        => 'webhook/{token}',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'declare  
v_body clob;  
begin  


v_body := telegram.blob2clob(:body);  
telegram.in_parse(v_body);  

bot_in_point;  
end;');

        
COMMIT;

END;